NAS-139006 / 25.10.2 / Add exception handling to set_ha_targets_sys (and retry) (by bmeagherix) (#17865)
Had an occurrence in the wild where an error was raised during a call to
`set_ha_targets_sys`:
```
OSError: [Errno 16] Device or resource busy
```
Handle these (or similar) better.

----
CI with no iSCSI regressions
[here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/sharing_protocols_tests/1129/).

Original PR: https://github.com/truenas/middleware/pull/17864

---------

Co-authored-by: Brian M <brian.meagher@ixsystems.com>