NAS-139837 / 26.0.0-BETA.1 / Change import behavior for atomic_write (#18226)
This commit adjusts when we try to import atomic_write so that it occurs
once we've rewritten the python path.

```
root@truenas[~]# cat /var/log/truenas-installer-initrd-error.log

======================================================================
Timestamp: 2026-02-16T21:25:46.469672
truenas-initrd.py completed with exit code 1
Error output:
Traceback (most recent call last):
  File "/tmp/tmpwl6etqoq/usr/local/bin/truenas-initrd.py", line 14, in <module>
    from middlewared.utils.io import atomic_write
ImportError: cannot import name 'atomic_write' from 'middlewared.utils.io' (/usr/lib/python3/dist-packages/middlewared/utils/io.py)

======================================================================
```