NAS-140109 / 26.0.0-BETA.1 / Fix enclosure alert (#18341)
mypy found the following error:
```
middlewared/alert/source/enclosure_status.py:96: error: Argument 1 to "remove" of "list" has incompatible type "str"; expected "list[str]"  [arg-type]
```

good_enclosures was a list of lists of single elements that contained
strings like `f"{enc['name']} (id: {enc['id']})"`. We were trying to:
* Remove strings from that list (which would always raise ValueError
since the list contains lists, not strings)
* List contained `f"{enc['name']} (id: {enc['id']})"`, we were trying to
remove just `enc_name`, that would never have worked also