python print error
The changes fixes the following error on freenas 11 with python 3.6.1
```
  File "/usr/local/bin/afpusers", line 97
    print "PID      UID      Username         Name                 Logintime Mac"
SyntaxError: Missing parentheses in call to 'print'
```
I do not know if it's a good way to copy the objects back ('bytes') and forth ('decode'), but it now works for me again. However, I did not carry out any major tests. So if someone should look at it. 
Thank you.