NAS-139956 / 26.0.0-BETA.1 / fix errno 40 in etc plugin (#18285)
We're getting this traceback on boot up of middlewared
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/plugins/etc.py", line 603, in make_changes
    changes = write_if_changed(full_path, rendered, tmpdir='/etc', **payload)
  File "/usr/lib/python3/dist-packages/middlewared/utils/io.py", line 262, in write_if_changed
    with open(truenas_os.openat2(path, os.O_RDONLY, resolve=truenas_os.RESOLVE_NO_SYMLINKS), 'rb+') as f:
              ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 40] Too many levels of symbolic links
```
This is because the `console-setup` version that ships in Trixie changed
it so that a symlink is created for /etc/vconsole.conf to point to
`/etc/default/keyboard` (cf.
[here](https://bugs-devel.debian.org/cgi-bin/bugreport.cgi?bug=1040650).)
We just need to remove the vconsole.conf entry.