NAS-138380 / 26.04 / Do not store datetime offsets in the configuration database (#17515)
Switching to SQLAlchemy 2.0, which stores datetime offset in the SQLite
database, introduced the crash:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 571, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 618, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 692, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 689, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/disk_/sync.py", line 144, in sync_all
    elif disk['disk_expiretime'] < utc_now():
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare offset-naive and offset-aware datetimes
```

All our codebase was written with the assumption that datetime offsets
are not stored in the database. Let's keep this behavior.