NAS-140310 / 27.0.0-BETA.1 / Also handle dicts in `get_mock_return_model` (#18468)
This fixes test_update.py::test_update failing with
```
AttributeError: 'dict' object has no attribute 'available'
```
Because `update.profile_choices` is expected to be a dict of objects,
but a dict of dicts is returned due to mocking.