NAS-141185 / 27.0.0-BETA.1 / mypy checks for pwenc plugin (#19028)
Additionally, a new `private_method` decorator was added to replace
`@private`, `@pass_app`, etc. decorators that cause
```
middlewared/plugins/pwenc.py:91: error: Untyped decorator makes function "replace" untyped  [misc]
```