NAS-140109 / 25.10.2.2 / Fix enclosure alert (by themylogin) (#18345)
mypy found the following error:
```
middlewared/alert/source/enclosure_status.py:96: error: Argument 1 to "remove" of "list" has incompatible type "str"; expected "list[str]"  [arg-type]
```

good_enclosures was a list of lists of single elements that contained
strings like `f"{enc['name']} (id: {enc['id']})"`. We were trying to:
* Remove strings from that list (which would always raise ValueError
since the list contains lists, not strings)
* List contained `f"{enc['name']} (id: {enc['id']})"`, we were trying to
remove just `enc_name`, that would never have worked also

Original PR: https://github.com/truenas/middleware/pull/18341

Co-authored-by: themylogin <themylogin@gmail.com>