NAS-138995 / 26.04 / fix KeyError crash in event unsubscribe (#17858)
Saw this in a debug from a customer. Looks like they're scripting
against the API and passing bad values to unsubscribe calls.
```
  File "/usr/lib/python3/dist-packages/middlewared/plugins/auth.py", line 1210, in logout
    await self.middleware.event_source_manager.unsubscribe_app(app)
  File "/usr/lib/python3/dist-packages/middlewared/common/event_source/manager.py", line 142, in unsubscribe_app
    await self.unsubscribe(ident)
  File "/usr/lib/python3/dist-packages/middlewared/common/event_source/manager.py", line 122, in unsubscribe
    ident_data = self.idents.pop(ident)
                 ^^^^^^^^^^^^^^^^^^^^^^
KeyError: '5de6d234-f8e5-4e3d-b862-fa4880a4edf940399bc1-f79f-4a8c-aa69-73ed928b3567'

(cherry picked from commit 5202f8017a9c5a709ee538217f9167b58817293a)