NAS-139611 / 26.0.0-BETA.1 / Fix LongStringWrapper.__eq__ crash (#18143)
```
[2026/02/03 10:11:36] (WARNING) middlewared.process_method_call():421 - Exception while calling user.query(*[[], {'order_by': ['builtin'], 'offset': 0, 'limit': 50}])
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/api/base/model.py", line 81, in _for_update_serializer
    (getattr(self, aliases[k]) != undefined) if k in aliases and hasattr(self, aliases[k])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/api/base/types/string.py", line 49, in __eq__
    return self.value == other.value
                         ^^^^^^^^^^^
AttributeError: 'Undefined' object has no attribute 'value'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/api/base/server/ws_handler/rpc.py", line 387, in process_method_call
    result = await method.call(app, id_, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/api/base/server/method.py", line 69, in call
    return await self._dump_result(app, methodobj, result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/api/base/server/method.py", line 72, in _dump_result
    return self.middleware.dump_result(self.serviceobj, methodobj, app, result)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1002, in dump_result
    return serialize_result(new_style_returns_model, result, expose_secrets, self.dump_result_allow_fallback)
  File "/usr/lib/python3/dist-packages/middlewared/api/base/handler/result.py", line 23, in serialize_result
    return model(result=result).model_dump(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        context={"expose_secrets": expose_secrets},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        warnings=False,
        ^^^^^^^^^^^^^^^
        by_alias=True,
        ^^^^^^^^^^^^^^
    )["result"]
    ^
  File "/usr/lib/python3/dist-packages/pydantic/main.py", line 426, in model_dump
    return self.__pydantic_serializer__.to_python(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<10 lines>...
        serialize_as_any=serialize_as_any,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
pydantic_core._pydantic_core.PydanticSerializationError: Error calling function `_for_update_serializer`: AttributeError: 'Undefined' object has no attribute 'value'
```